api_platform:
    title: An awesome Movie API
    version: 1.0.0
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        csv: [ 'text/csv' ]
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_client_items_per_page: true
        collection:
            pagination:
                items_per_page_parameter_name: itemsPerPage # Default value
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
